name: 'test'
on:
  workflow_dispatch:
#   push:
#     branches:
#       - master
#       - santiago-pr
# comment is test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run action
        id: run_action
        run: echo '::set-output name=my_output::world'
      - name: crash
        run: justcrash
      - name: log action output
        run: echo ${{steps.run_action.outputs.my_output}}
