name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
      - name: log action output
        run: echo ${{steps.run_action.outputs.my_output}}

